version: '3.1'

services:
  web:
    hostname: web
    image: apache:latest
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html/
    networks:
      docnet:
        ipv4_address: 10.5.0.10

  db:
    hostname: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./db:/var/lib/mysql
    networks:
      docnet:
        ipv4_address: 10.5.0.11

  ssh:
    hostname: ssh
    image: faultysshd
    restart: always
    networks:
      docnet:
        ipv4_address: 10.5.0.20

networks:
  docnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
